### PR TITLE
Fix epochtime localized

### PR DESCRIPTION
**Pull request by brettveenstra**
fix for Issue #1

### CODE REVIEW

**Comment by jdemeuse1204** [comment]
Looks good, thank you for the fixes

**Comment by brettveenstra** [comment]
Cool... do you have a CI to Nuget to get this fix published?  :)

**Comment by jdemeuse1204** [comment]
Sure do! :).  I am creating a 1.0.1 branch right now to handle the fix

**Comment by jdemeuse1204** [comment]
1.0 was not merged into master.  That's my fault, I should have done that when I published 1.0.... derp.  Anyways, I merged 1.0 into master and merged your changes into it, so we are all good.  It was mostly name changes and some encryption stuff. Looking into your suggested claims resolution now :)

**Pull request merged**
